# Generated by Django 5.0.7 on 2024-10-09 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0017_group_of_products_parent_alter_products_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('Продажа', 'Продажа'), ('Пополнение', 'Пополнение'), ('Создание товара', 'Создание товара')], default='Движение', max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('created_timestamp', models.DateTimeField(auto_now_add=True)),
                ('quantity_change', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='products.products')),
            ],
        ),
    ]
