# Generated by Django 5.0.7 on 2024-08-01 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_products_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='size',
            field=models.CharField(choices=[('20 cm', '20 cm'), ('30 cm', '30 cm'), ('40 cm', '40 cm'), ('50 cm', '50 cm'), ('60 cm', '60 cm'), ('70 cm', '70 cm'), ('80 cm', '80 cm'), ('100 cm', '100 cm'), ('110 cm', '110 cm'), ('120 cm', '120 cm'), ('130 cm', '130 cm'), ('140 cm', '140 cm'), ('150 cm', '150 cm')], default=20, max_length=250),
        ),
    ]
