# Generated by Django 5.0.7 on 2024-08-01 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_group_of_products_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='products', to='products.group_of_products'),
        ),
    ]
