# Generated by Django 5.0.7 on 2024-09-12 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_category_products_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Categories',
        ),
    ]
