# Generated by Django 5.0.7 on 2024-09-18 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_alter_products_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='purchase_prise',
        ),
        migrations.RemoveField(
            model_name='products',
            name='sale_prise',
        ),
        migrations.AddField(
            model_name='products',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='Себестоимость'),
        ),
        migrations.AddField(
            model_name='products',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='Цена'),
        ),
    ]
