# Generated by Django 5.0.7 on 2024-09-19 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_remove_products_purchase_prise_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group_of_products',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subgroups', to='products.group_of_products'),
        ),
        migrations.AlterField(
            model_name='products',
            name='size',
            field=models.CharField(blank=True, choices=[('20 cm', '20 cm'), ('40 cm', '40 cm'), ('60 cm', '60 cm'), ('80 cm', '80 cm'), ('100 cm', '100 cm'), ('130 cm', '130 cm'), ('150 cm', '150 cm')], default=20, max_length=250),
        ),
    ]
